### ISSUE TITLE
Method not found error

### ISSUE THREAD

**Issue by wassimj** [hypar-io/FunctionBuilder#13]
Just trying out a "Hello World".. First time around, it all worked fine. I built a TestFunction that displayed a cube. I went into code and simply changed the height from 1.0 to 0.5 and ran the Hypar: run task. It gave me the following error:
There was an error executing the function.
Exception has been thrown by the target of an invocation.
Method not found: 'Elements.Geometry.Polygon Elements.Geometry.Polygon.Rectangle(Double, Double)'.
   at TestFunction.TestFunction.Execute(Dictionary`2 inputModels, TestFunctionInputs input)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Hypar.Commands.RunCommand.ExecuteFunction(String functionName, String functionDir, Boolean newBuild) in /Users/ikeough/Documents/Hypar/Hypar/CLI/src/Commands/RunCommand.cs:line 308

**Comment by wassimj** [comment]
![image](https://user-images.githubusercontent.com/6302909/74633817-6f092c00-515a-11ea-947d-ecad61d0047c.png)

**Comment by wynged** [comment]
Turns out the Hypar CLI needed to be updated using 
`dotnet tool update -g hypar.cli` 
The task Hypar run actually runs the HyparCLI command `hypar run` so it relies on the CLI being up to date.
